name: Check cached Setup

on: 
  #push: 
  schedule:
    - cron: '0 1 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:

  build_iverilog:
    uses: ./.github/workflows/setup_iverilog.yml
  check_iverilog:
    runs-on: ubuntu-latest
    needs: build_iverilog
    steps:
      - name: Cache Icarus
        uses: actions/cache@v3
        with:
          path: ${{ needs.build_iverilog.outputs.cache_dir }}
          key: ${{ needs.build_iverilog.outputs.cache_key }}
      - name: Add to PATH
        run: |
          echo "${{ needs.build_iverilog.outputs.cache_dir }}/bin" >> $GITHUB_PATH
      - name: Report Icarus
        run: |
          which iverilog
